pipeline {
    agent any
    stages {
        stage('Сборка') {
            steps {
                echo 'Компиляция проекта...'
            }
        }
        stage('Тестирование') {
            steps {
                echo 'Запуск тестов...'
            }
        }
        stage('Развёртывание') {
            steps {
                echo 'Деплой на сервер...'
            }
        }
    }
}
