apiVersion: v1
kind: Service
metadata:
  name: testj
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: testj
status:
  loadBalancer: {}